apiVersion: v2
name: unleash
description: Unleash is a open source feature flag & toggle system, that gives you a great overview over all feature toggles across all your applications and services.
icon: https://docs.getunleash.io/img/logo.svg

type: application

version: 6.0.0

appVersion: "7.3.0"

dependencies:
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.26.1
    condition: cnpg.enabled

maintainers:
  - name: evanstucker-hates-2fa
  - name: ivarconr
    email: ivarconr@gmail.com

sources:
  - https://github.com/Unleash/unleash
  - https://github.com/Unleash/helm-charts
