{{- if .Values.unleash.generateAdminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unleash-enterprise.fullname" . }}-admin-secret
type: Opaque
{{- $secretName := printf "%s-admin-secret" (include "unleash-enterprise.fullname" .) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $password := "" }}
{{- if $secret }}
  {{- $password = index $secret.data "password" | b64dec }}
{{- else }}
  {{- $password = randAlphaNum 32 }}
{{- end }}
stringData:
  password: {{ $password | quote }}
{{- end }}
