{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ ternary "policy/v1" "policy/v1beta1" (.Capabilities.APIVersions.Has "policy/v1") }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "unleash-enterprise.fullname" . }}
  labels:
    {{- include "unleash-enterprise.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: 0
  {{- end }}
  selector:
    matchLabels:
      {{- include "unleash-enterprise.selectorLabels" . | nindent 6 }}
{{- end }}
