{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unleash-enterprise.fullname" . }}
  labels:
{{ include "unleash-enterprise.labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}
