{{- if and .Values.serviceAccount .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unleash-enterprise.serviceAccountName" . }}
  labels:
    {{- include "unleash-enterprise.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
