---
apiVersion: v2
name: unleash-edge
description: A Helm chart for deploying Unleash Edge to kubernetes
icon: https://docs.getunleash.io/img/logo.svg
type: application
version: 2.0.3

appVersion: "v11.0.2"
maintainers:
  - name: chriswk
  - name: sighphyre
  - name: nunogois
  - name: gastonfournier
