---
apiVersion: v2
name: unleash-edge
description: A Helm chart for deploying Unleash Edge to kubernetes

type: application
version: 0.1.0

appVersion: "v0.1.0"
maintainers:
  - name: chriswk
  - name: sighphyre
  - name: nunogois
  - name: gastonfournier
