apiVersion: v2
name: unleash-edge
description: A Helm chart for deploying Unleash Edge to kubernetes
icon: https://docs.getunleash.io/img/logo.svg

type: application

version: 3.1.1
appVersion: "v20.1.1"


maintainers:
  - name: chriswk
  - name: sighphyre
  - name: nunogois
  - name: gastonfournier

sources:
  - https://github.com/Unleash/unleash-edge
  - https://github.com/Unleash/helm-charts
