{{- if .Values.cnpg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.cluster.name }}-db-secret
type: Opaque
stringData:
  username: {{ .Values.cnpg.cluster.owner }}
  password: {{ randAlphaNum 32 | quote }}
{{- end }}
