{{- if .Values.cnpg.cluster.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.cluster.name }}-db-secret
type: Opaque
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-db-secret" .Values.cnpg.cluster.name)) }}
{{- $password := "" }}
{{- if $secret }}
  {{- $password = index $secret.data "password" | b64dec }}
{{- else }}
  {{- $password = randAlphaNum 32 }}
{{- end }}
stringData:
  username: {{ .Values.cnpg.cluster.owner }}
  password: {{ $password | quote }}
{{- end }}
